project:
  type: website

website:
  title: "site"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - code/Binary_Classification.ipynb
      - code/DL.ipynb
      - code/CNN.ipynb

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



